### ISSUE TITLE
Ошибка 404 при открытии страниц в новой вкладке

### ISSUE THREAD

**Issue by kerastinell** [innereq/092918.xyz#17]
Шаги по воспроизведению проблемы:

1. Открыть главную страницу https://092918.xyz/ru/
2. Находясь на главной, перейти на другую страницу, например, "Сервисы" -> "Серверы"
3. Открыть любую ссылку (например, "Email") в новой вкладке и параллельно перейти по ней в существующей вкладке
4. Результат: текущая вкладка нормально отобразит страницу, а другая вкладка с тем же адресом вернёт 404

Проверено в Firefox 67

**Comment by commagray** [comment]
Что интересно, оно не воспроизводится на встроенном в VuePress веб-сервере.

**Comment by commagray** [comment]
Это баг в плагине clean-urls. Он неактивен долгое время, поэтому репортить нет смысла.

Вернул исходное поведение роутера в 0482d56463e479a95a738e43f9edac4972502bfe.
