### ISSUE TITLE
Ссылки на Telegram-прокси без random padding

### ISSUE THREAD

**Issue by kerastinell** [innereq/092918.xyz#18]
Замечено в:

1. [(RU) mtproxy.md](https://github.com/innereq/092918.xyz/blob/master/site/ru/how/mtproxy.md)
2. [(EN) mtproxy.md](https://github.com/innereq/092918.xyz/blob/master/site/how/mtproxy.md)

Random padding - "изкоробочная" фича MTProxy, которая позволяет обходить DPI в странах, где блокируется Telegram. Для активации достаточно приписать `dd` перед секретом.

Предлагаемое решение: в ссылке для прокси перед значением параметра secret дописать `dd` (получится **dd**5f20f9... **dd**52fe42... **dd**5fc245...). К слову, некоторые форки MTProxy вовсе запрещают подключение без random padding.

**Comment by commagray** [comment]
В следующий раз можешь делать PR по таким мелким изменениям.
